name: dj

services:
  storage:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'  
          memory: 1024M      
        reservations:
          cpus: '0.25'       
          memory: 512M
    
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  minio-data:
  postgres-data:
